name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: Run tests
      - run: python -m pip install --upgrade pip
             pip install ruff pytest
        run: pytest TP1/test.py
